26/GodWillHelpMe/Models/PermissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GodWillHelpMe.Models
{
    public class PermissionViewModel
    {
        public string RoleId { get; set; }
        public IList<RoleClaimsViewModel> RoleClaims { get; set; }
    }
}

26/GodWillHelpMe/Models/UserRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GodWillHelpMe.Models
{
    public class UserRolesViewModel
    {
        public string RoleName { get; set; }
        public bool Selected { get; set; }
    }
}

26/GodWillHelpMe/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GodWillHelpMe.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

26/GodWillHelpMe/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GodWillHelpMe.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

26/GodWillHelpMe/Pages/Permission.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GodWillHelpMe.Helpers;
using GodWillHelpMe.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GodWillHelpMe.Pages
{
    [Authorize(Roles ="SuperAdmin")]
    public class PermissionModel : PageModel
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public PermissionModel(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public async Task OnGet(string roleId)
        {
            var model = new PermissionViewModel();
            var AllPermissions = new List<RoleClaimsViewModel>();
            AllPermissions.GetPermissions(typeof(Permissions.Permissions.Products), roleId);
            var role = await roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await roleManager.GetClaimsAsync(role);
            var allClaimValues = AllPermissions.Select(a => a.Value).ToList();
            var roleClaimValues = claims.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();
            foreach (var permission in AllPermissions)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = AllPermissions;
        }
        public async Task<IActionResult> OnPostUpdate(PermissionViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.RoleId);
            var claims = await roleManager.GetClaimsAsync(role);
            foreach (var claim in claims)
            {
                await roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await roleManager.AddPermissionClaim(role, claim.Value);
            }
            return RedirectToPage("Permission", new { roleId = model.RoleId });
        }
    }
}

26/GodWillHelpMe/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GodWillHelpMe.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

26/GodWillHelpMe/Pages/Product.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GodWillHelpMe.Pages
{
    public class ProductModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

26/GodWillHelpMe/Pages/Roles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace GodWillHelpMe.Pages
{
    [Authorize(Roles="SuperAdmin")]
    public class RolesModel : PageModel
    {
        private readonly RoleManager<IdentityRole> role;
        
        public RolesModel(RoleManager<IdentityRole> role)
        {
            this.role = role;
        }
        public async Task OnGetAsync()
        {
            var roles = await role.Roles.ToListAsync();
        }
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await role.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToPage("/Roles");
        }
    }
}

26/GodWillHelpMe/Pages/UserRoles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GodWillHelpMe.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GodWillHelpMe.Pages
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserRolesModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRolesModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public async Task Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                viewModel.Add(userRolesViewModel);
            }
            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };
           
        }
        public async Task<IActionResult> OnPostUpdate(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            await Seeds.DefaultUsers.SeedSuperAdminAsync(_userManager, _roleManager);
            return RedirectToPage("/UserRoles", new { userId = id });
        }
    }
}

26/GodWillHelpMe/Pages/Users.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace GodWillHelpMe.Pages
{
    [Authorize]
    public class UsersModel : PageModel
    {
        
        private readonly UserManager<IdentityUser> userManager;
        
        public UsersModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task OnGetAsync()
        {
            var CurrentUser =await userManager.GetUserAsync(HttpContext.User);
            var allUserExceptCurrentUser = await userManager.Users.Where(a => a.Id != CurrentUser.Id).ToListAsync();
        }
    }
}

26/GodWillHelpMe/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

26/GodWillHelpMe/Pages/Permission.cshtml
@page
@model Models.PermissionViewModel
<h1>Permissions</h1>
<br />
<div class="card">
    <div id="viewAll" class="card-body table-responsive">
        <form  method="post"  class="d-inline" asp-route-id="@Model.RoleId"asp-page-handler="update">
            <input asp-for="@Model.RoleId" type="hidden"  />
            <table class="table table-striped" id="permissionTable">
                <thead>
                    <tr>
                        <th>
                            Type
                        </th>
                        <th>
                            Permission
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.RoleClaims.Count(); i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="@Model.RoleClaims[i].Type" type="hidden" />
                                @Model.RoleClaims[i].Type
                            </td>
                            <td>
                                <input asp-for="@Model.RoleClaims[i].Value" type="hidden" />
                                @Model.RoleClaims[i].Value
                            </td>
                            <td>
                                <div class="form-check m-1">
                                    <input asp-for="@Model.RoleClaims[i].Selected" class="form-check-input" />
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-sm-12" style="padding: 20px 20px 0px 0px">
                <button type="submit" id="save" class="btn btn-success">
                    <i class="fa fa-check"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</div>

26/GodWillHelpMe/Pages/Product.cshtml
@page
@model GodWillHelpMe.Pages.ProductModel
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using Constants
<h1>Product Management</h1>
<br />
@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Permissions.Products.Create)).Result.Succeeded)
{
    <button class="btn btn-success">Create</button>
}
@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Permissions.Products.View)).Result.Succeeded)
{
    <button class="btn btn-info">View</button>
}
@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Permissions.Products.Edit)).Result.Succeeded)
{
    <button class="btn btn-warning">Modify</button>
}
@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Permissions.Products.Delete)).Result.Succeeded)
{
    <button class="btn btn-danger">Delete</button>
}

26/GodWillHelpMe/Pages/Roles.cshtml
@page
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
@{
}
<h1>Roles</h1>
<br />
<form method="post">
    <div class="input-group">
        <input name="roleName" class="form-control w-25">
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>
<table class="table table-striped" id="roleTable">
    <thead>
        <tr>
            <th>
                Role
            </th>
            <th>
                Id
            </th>
            <th style="width:10%">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>
                    @role.Name
                </td>
                <td>
                    @role.Id
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a class="dropdown-item">
                                <i class="fas fa-pencil-alt"></i> Edit
                            </a>
                            <form class="d-inline">
                                <a class="dropdown-item"><i class="fas fa-trash-alt"></i> Delete</a>
                            </form>
                            @if (role.Name != "SuperAdmin")
                            {
                                <a style='margin-right:16px' asp-page="Permission"  asp-route-roleId="@role.Id" class="dropdown-item">
                                    <i class="fas fa-wrench"></i> Manage Permissions
                                </a>
                            }
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

26/GodWillHelpMe/Pages/UserRoles.cshtml
@page
@model GodWillHelpMe.Models.ManageUserRolesViewModel
<h3>Manage Roles for @Model.UserId</h3>
<br />
<div class="card">
    <div id="viewAll" class="card-body table-responsive">
        <form asp-page-handler="update" method="post"  asp-route-id="@Model.UserId" class="d-inline">
            <input asp-for="@Model.UserId" type="hidden" />
            <table class="table table-striped" id="userRolesTable">
                <thead>
                    <tr>
                        <th>
                            Role
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.UserRoles.Count(); i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="@Model.UserRoles[i].RoleName" type="hidden" />
                                @Model.UserRoles[i].RoleName
                            </td>
                            <td>
                                <div class="form-check m-1">
                                    <input asp-for="@Model.UserRoles[i].Selected" class="form-check-input" />
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-sm-12" style=" padding: 20px 20px 0px 0px">
                <button type="submit" id="save" class="btn bg-primary">
                    <i class="fa fa-check"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</div>

26/GodWillHelpMe/Pages/Users.cshtml
@page
@model IEnumerable<IdentityUser>
@{
}
<h1>User List</h1>
<br />
<table class="table table-striped" id="userTable">
    <thead>
        <tr>
            <th>
                User
            </th>
            <th>
                Email
            </th>
            <th style="width:10%">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    <div class="row">
                        <div class="col-sm">
                            <a>
                                @user.UserName
                            </a>
                            <br>
                            <small>
                                @user.Id
                            </small>
                        </div>
                    </div>
                </td>
                <td>
                    <a>
                        @user.Email
                    </a>
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a style='margin-right:16px' asp-page="UserRoles" asp-route-userId="@user.Id" class="dropdown-item">
                                <i class="fas fa-wrench"></i> Manage Roles
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>